name: worldtime
description: World Time Plugin uses a free public API to access local time info for a specific 
  geolocation or TZ time zone.
version: 1.2.2
homepage: https://github.com/MiroslavZB/world-time.git

environment:
  sdk: ">=3.0.0 <3.7.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.worldtime.worldtime
        pluginClass: WorldtimePlugin
      ios:
        pluginClass: WorldtimePlugin
      web:
        pluginClass: WorldtimePlugin
        fileName: worldtime.dart
      macos:
        pluginClass: WorldtimePlugin
      windows:
        pluginClass: WorldtimePlugin
      linux:
        pluginClass: WorldtimePlugin

